{
  "type": "record",
  "name": "PdmCommand",
  "namespace": "com.um6p.pdm.commands",
  "fields": [
    {
      "name": "commandType",
      "type": {
        "type": "enum",
        "name": "CommandType",
        "symbols": ["TRAIN", "INFER", "STOP", "PAUSE", "UNPAUSE"]
      }
    },
    { "name": "forecastId", "type": "string" },
    {
      "name": "modelType",
      "type": [
        "null",
        {
          "type": "enum",
          "name": "ModelType",
          "symbols": ["ANOMALY", "FORECAST", "BOTH"]
        }
      ],
      "default": null
    },
    { "name": "deviceId", "type": ["null", "string"], "default": null },
    {
      "name": "timestamp",
      "type": { "type": "long", "logicalType": "timestamp-millis" }
    },
    { "name": "commandId", "type": ["null", "string"], "default": null }
  ]
}
