# syntax=docker/dockerfile:1.7

# syntax=docker/dockerfile:1.7
FROM node:22-slim AS node

FROM eclipse-temurin:21-jdk AS build

WORKDIR /workspace/tb-quarkus/gateway

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
 && ln -s /usr/local/lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

COPY tb-quarkus/gateway/gradlew tb-quarkus/gateway/gradlew.bat tb-quarkus/gateway/settings.gradle tb-quarkus/gateway/build.gradle tb-quarkus/gateway/gradle.properties ./
COPY tb-quarkus/gateway/gradle ./gradle
COPY tb-quarkus/gateway/src ./src
COPY api-specs /workspace/api-specs

RUN --mount=type=cache,target=/root/.gradle \
    --mount=type=cache,target=/root/.npm \
    chmod +x ./gradlew \
    && ./gradlew --no-daemon --info --stacktrace --warning-mode all build -Dquarkus.package.jar.type=fast-jar -x test

FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24

ENV LANGUAGE='en_US:en'

COPY --from=build --chown=185 /workspace/tb-quarkus/gateway/build/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 /workspace/tb-quarkus/gateway/build/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 /workspace/tb-quarkus/gateway/build/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 /workspace/tb-quarkus/gateway/build/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8081
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Dquarkus.http.port=8081 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT ["/opt/jboss/container/java/run/run-java.sh"]
