services:
  pdm-forecast-worker:
    build:
      context: ./predictive-maintenance
      dockerfile: .Dockerfile
    volumes:
      - .:/app
      - ./pip-cache:/root/.cache/pip
      - ./models-cache:/models
    depends_on:
      tb-quarkus:
        condition: service_healthy
      thingsboard:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PDM_PROCESS_ROLE=worker
      - PDM_WORKER_MODEL_TYPE=FORECAST
      - PDM_WORKER_GROUP=pdm-python-forecast-workers
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - REDIS_URL=redis://redis:6379/0
      - QUARKUS_API_URL=http://tb-quarkus:8081/api/v1
      - TB_HOST=${TB_HOST:-http://thingsboard:8080}
      - TB_USERNAME=${TB_USERNAME:-tenant@thingsboard.org}
      - TB_PASSWORD=${TB_PASSWORD:-tenant}
      - MODELS_PATH=/models
      - PDM_AVRO_SCHEMA_DIR=/app/tb-quarkus/gateway/src/main/avro
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

  pdm-anomaly-worker:
    build:
      context: ./predictive-maintenance
      dockerfile: .Dockerfile
    volumes:
      - .:/app
      - ./pip-cache:/root/.cache/pip
      - ./models-cache:/models
    depends_on:
      tb-quarkus:
        condition: service_healthy
      thingsboard:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PDM_PROCESS_ROLE=worker
      - PDM_WORKER_MODEL_TYPE=ANOMALY
      - PDM_WORKER_GROUP=pdm-python-anomaly-workers
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - REDIS_URL=redis://redis:6379/0
      - QUARKUS_API_URL=http://tb-quarkus:8081/api/v1
      - TB_HOST=${TB_HOST:-http://thingsboard:8080}
      - TB_USERNAME=${TB_USERNAME:-tenant@thingsboard.org}
      - TB_PASSWORD=${TB_PASSWORD:-tenant}
      - MODELS_PATH=/models
      - PDM_AVRO_SCHEMA_DIR=/app/tb-quarkus/gateway/src/main/avro
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
