services:
  go-toolbox-interpreter:
    build:
      context: ./go-toolbox
      dockerfile: Dockerfile
      target: base
    working_dir: /src
    volumes:
      - ./go-toolbox:/src
      - ./go-mod-cache:/go/pkg/mod
      - ./go-build-cache:/root/.cache/go-build
    environment:
      - TB_USERNAME=${TB_USERNAME}
      - TB_PASSWORD=${TB_PASSWORD}
    stdin_open: true
    tty: true
    command: go run .
    depends_on:
      thingsboard:
        condition: service_healthy

  go-toolbox-dash:
    build:
      context: ./go-toolbox
      dockerfile: Dockerfile
      target: dash
    volumes:
      - ./go-mod-cache:/go/pkg/mod
      - ./go-build-cache:/root/.cache/go-build
    depends_on:
      thingsboard:
        condition: service_healthy
    command: /go/bin/dash

  go-toolbox-darktheme:
    build:
      context: ./go-toolbox
      dockerfile: Dockerfile
      target: darktheme
    volumes:
      - ./ui-ngx/src:/ui-ngx/src  # adjust to your actual ui-ngx path

